# Generated by Django 6.0.6 on 2026-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_user_phone_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Идет обучение'), ('end', 'Обучение завершено')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='transport',
            field=models.CharField(choices=[('bus', 'Автобус'), ('trolley', 'Электробус'), ('tram', 'Трамвай')], default='bus', max_length=20),
        ),
    ]
